%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Author: Hardik Y. Patil                                                      %
% Email: hardikyp@umich.edu                                                    %
% Date: February 26, 2026                                                      %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
% This function assigns a piecewise linear and nonlinear behavior to a 
% torsional spring. The spring behaves linearly for alpha in the range 
% [alpha1, alpha2]. When alpha is outside this range, the constitutive law
% transitions to asymptotic branches.
%
% By default (delta = 0), the asymptotes are at alpha = 0 and alpha = 2*pi.
% If delta > 0, the asymptotes are shifted inward to:
%   left  bound: alpha = delta
%   right bound: alpha = 2*pi - delta
% so stiffness and moment grow unbounded before reaching 0 or 2*pi.
%
% Inputs:
% -------
% k0 (float): Baseline rotational spring stiffness in the linear region.
% alpha (float): Current relative angle of the torsional spring (rad).
% alpha0 (float): Resting relative angle of the torsional spring (rad).
% alpha1 (float): Lower transition angle between responses (rad).
% alpha2 (float): Upper transition angle between responses (rad).
% delta (float): Inward shift of asymptotic limits (rad). 
%
% Outputs:
% --------
% kT (array): Modified spring stiffness
% M (array): Modified moment generated by the spring
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [kT, M] = enrichedSpringLaw(k0, alpha, alpha0, alpha1, alpha2, delta)
if ~(0 <= delta && delta < alpha1 && alpha1 < alpha2 && alpha2 < 2*pi-delta)
    error('Require 0 <= delta < alpha1 < alpha2 < 2*pi-delta');
end

if delta > 0
    epsA = 1e-12;
    alpha = min(max(alpha, delta + epsA), 2*pi - delta - epsA);
end

if alpha < alpha1
    aL = pi / (2*(alpha1 - delta));
    xi = aL * (alpha - alpha1);
    M  = k0*(alpha1 - alpha0) + (k0/aL)*tan(xi);
    kT = k0*sec(xi)^2;
elseif alpha <= alpha2
    M  = k0*(alpha - alpha0);
    kT = k0;
else
    aR = pi / (2*((2*pi - delta) - alpha2));
    xi = aR * (alpha - alpha2);
    M  = k0*(alpha2 - alpha0) + (k0/aR)*tan(xi);
    kT = k0*sec(xi)^2;
end
end