%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Author: Hardik Y. Patil                                                      %
% Email: hardikyp@umich.edu                                                    %
% Date: February 26, 2026                                                      %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
% This function assigns a piecewise linear and nonlinear behaviour to the 
% torsional spring. The spring behaves linearly for alpha in the range 
% [alpha1, alpha2]. When alpha is less than alpha 1 or more than alphalpha2, 
% the spring stiffness will increase to infinity asymptotically as alpha goes 
% to 0 or 2*pi, respectively.
% 
% Inputs:
% -------
% k0 (float): Rotational spring stiffness for each spring
% alpha1 (float): Current relative angle of the torsional spring (rad)
% alpha2 (float): Current relative angle of the torsional spring (rad)
% alpha (float): Current relative angle of the torsional spring (rad)
% alpha0 (float): Resting relative angle of the torsional spring (rad)
%
% Outputs:
% --------
% kT (array): Modified spring stiffness
% M (array): Modified moment generated by the spring
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [kT, M] = enrichedSpringLaw(k0, alpha, alpha0, alpha1, alpha2)
if alpha < alpha1
    xi = pi * (alpha - alpha1) / (2 * alpha1);
    M  = k0 * (alpha1 - alpha0) + (2 * k0 * alpha1 / pi) * tan(xi);
    kT = k0 * sec(xi)^2;
elseif alpha <= alpha2
    M  = k0 * (alpha - alpha0);
    kT = k0;
else
    xi = pi * (alpha - alpha2) / (4 * pi - 2 * alpha2);
    M  = k0 * (alpha2 - alpha0) + (2 * k0 * (2 * pi - alpha2) / pi) * tan(xi);
    kT = k0 * sec(xi)^2;
end
end